[package]
name = "cctv_360_degrees"
version = "0.1.0"
authors = ["Maxim <maxim230898@yandex.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.0"
xml-rs = "0.8.0"
url = "2.1.1"
uuid = { version = "0.8", features = ["v4"] }
rand = "0.7"
sha1 = "0.6.0"
chrono = "0.4.10"
reqwest = "0.10.1"
base64 = "0.11.0"
tungstenite = "0.10.1"
tokio = { version = "0.2.11", features = ["full"] }
async-trait = "0.1.24"
serde = "1.0.104"
serde_json = "1.0.48"
futures = "0.3"
actix-web = "2.0.0"
actix-rt = "1"